# Generated by Django 4.2.4 on 2023-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historyplacedetail_image1_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mijoz ismi: ')),
                ('email', models.CharField(max_length=150, verbose_name='Mijoz email pochtasi: ')),
                ('description', models.TextField(verbose_name='Mijoz matni: ')),
            ],
        ),
    ]
